### PR TITLE
LRQA-75763

### PR DESCRIPTION
**Pull request by catarineaguiar**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:help

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by pyoo47** [comment]
ci:test:dl-store

**Comment by pyoo47** [comment]
Looks like `az login` ran but didn't work for some reason.

```
login-azure-cli:
     [exec] ERROR: AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials.
     [exec] Trace ID: 81b9ffd5-84c9-4eb0-9af2-b41f92c32101
     [exec] Correlation ID: 7aa13479-d320-414a-9632-d26518a2a1f6
     [exec] Timestamp: 2022-11-09 22:35:48Z
     [exec] To re-authenticate, please run:
     [exec] az login
     [exec] Result: 1
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1378951170.properties

create-azure-container:
     [exec] Result: 1
     [echo] ERROR: Please run 'az login' to setup account.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1378951170.properties

```

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by vicnate5** [comment]
Creds are merged.

See https://github.com/catarineaguiar/liferay-portal/pull/51

**Pull request closed without merging**
