### PR TITLE
LRQA-75763 Azure store

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:dl-store:nocompile

**Comment by vicnate5** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
`[exec] ERROR: AADSTS50126: Error validating credentials due to invalid username or password.`

**Comment by vicnate5** [comment]
@catarineaguiar I am getting that same error locally, can you look into it?

**Comment by vicnate5** [comment]
@catarineaguiar Now I am getting something else locally
```
create-azure-container:
     [exec] Result: 1
     [echo] ERROR: AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2022-09-15T01:06:52.8440577Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2022-11-16T12:41:38.0000000Z'.
     [echo] Trace ID: f30942ff-015b-480a-a96f-4499b4e01b00
     [echo] Correlation ID: 1c8ab7b1-4a89-4760-8e06-e8b4697f63af
     [echo] Timestamp: 2022-11-17 21:20:49Z
     [echo] Interactive authentication is needed. Please run:
     [echo] az login --scope https://storage.azure.com/.default
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2004783097.properties
   ```

**Comment by catarineaguiar** [comment]
I think they changed the password

**Comment by catarineaguiar** [comment]
I'm going to re-open the ticket asking for an account.

**Pull request closed without merging**
