### PR TITLE
LRQA-82460

### PR DESCRIPTION
**Pull request by catarineaguiar**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
@zhangyan0701 I'm getting an error on to authenticate GCS on CI. Do you mind checking the credentials on CI repo, since I don't have access to that.

`java.lang.IllegalStateException: Unable to initialize GCS store`
`Caused by: java.io.IOException: Invalid PKCS#8 data.`

It might be related to the scapes in the credentials

**Comment by zhangyan0701** [comment]
@catarineaguiar The credentials on CI repo are correct. The issue is that the gcs property names that used here https://github.com/liferay/liferay-portal/blob/master/build-test.xml#L2985 are different from CI repo. I updated them and worked on my local. Testing here https://github.com/zhangyan0701/liferay-portal/pull/572.

**Comment by catarineaguiar** [comment]
Thanks a lot @zhangyan0701 <3

**Pull request closed without merging**
