### PR TITLE
LRAC-9290

### PR DESCRIPTION
**Pull request by catarineaguiar**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud:nocompile

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud

**Comment by catarineaguiar** [comment]
ci:help

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud:nocompile

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud:nocompile

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud:nocompile

**Comment by ViniLopes20** [comment]
ci:close

**Pull request closed without merging**
